
export const indianBanks: string[] = [
  "State Bank of India",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "Punjab National Bank",
  "Bank of Baroda",
  "Canara Bank",
  "Union Bank of India",
  "Bank of India",
  "IndusInd Bank",
  "Yes Bank",
  "IDBI Bank",
  "Central Bank of India",
  "Indian Bank",
  "UCO Bank",
  "Bank of Maharashtra",
  "Punjab & Sind Bank",
  "South Indian Bank",
  "Federal Bank",
  "Karur Vysya Bank",
  "IDFC First Bank",
  "Jammu & Kashmir Bank",
  "City Union Bank",
  "Bandhan Bank",
  "RBL Bank",
  "CSB Bank",
  "DCB Bank",
  "Dhanlaxmi Bank",
  "Nainital Bank",
  "Karnataka Bank",
  "Lakshmi Vilas Bank",
  "Tamilnad Mercantile Bank",
  "AU Small Finance Bank",
  "Equitas Small Finance Bank",
  "Ujjivan Small Finance Bank",
  "Paytm Payments Bank",
  "Airtel Payments Bank",
  "Fino Payments Bank",
  "India Post Payments Bank",
];
